export const MAX_CONTAINERS_QUANTITY_PER_REQUEST = 20;
export const TRACKING_CODE_SEQUENCE = 'TrackingCode';
export enum TRANSACTIONS_TYPES {
  RECOVER = 'RECOVER',
  DELETE_CONTAINERS = 'DELETE_CONTAINERS',
  TRANSFER_REQUEST = 'TRANSFER_REQUEST',
  TRANSFER_ACCEPT = 'TRANSFER_ACCEPT',
  TRANSFER_REJECT = 'TRANSFER_REJECT',
  TRANSFER_CANCEL = 'TRANSFER_CANCEL',
  TRANSPORT = 'TRANSPORT',
  TRANSPORT_CANCEL = 'TRANSPORT_CANCEL',
  TRANSPORT_ACCEPT = 'TRANSPORT_ACCEPT',
  TRANSPORT_REJECT = 'TRANSPORT_REJECT',
  PROCESS = 'PROCESS', // TODO
  COMPLETE = 'COMPLETE', // TODO
  REJECT = 'REJECT', // TODO
}

export enum CONTAINER_STATUS {
  RECOVERED = 'RECOVERED',
  DELETED = 'DELETED',
  TRANSFER_PENDING = 'TRANSFER_PENDING',
  TRANSFER_REJECTED = 'TRANSFER_REJECTED', // not neccesary
  TRANSFERRED = 'TRANSFERRED',
  IN_TRANSIT = 'IN_TRANSIT',
  IN_PROCESS = 'IN_PROCESS',
  COMPLETED = 'COMPLETED',
}
export enum NOTIFICATION_TYPES {
  TRANSFER_REQUEST = 'TRANSFER_REQUEST',
  TRANSFER_ACCEPT = 'TRANSFER_ACCEPT',
  TRANSFER_REJECT = 'TRANSFER_REJECT',
  TRANSFER_CANCEL = 'TRANSFER_CANCEL',
  TRANSPORT = 'TRANSPORT',
}

export enum RETRIBUTION_TYPES {
  MATERIAL = 'MATERIAL',
  TRANSPORT = 'TRANSPORT',
}

export enum PAYMENT_TRANSACTION_STATUS_TYPES {
  DRAFT = 'DRAFT',
  PAID = 'PAID',
  REJECTED = 'REJECTED',
}

export enum CRYPTOS_SYMBOL_TYPES {
  JELLYCOIN = 'JYC',
}
